#!/usr/bin/env bash
# displays numbers from 1 to 100, write fizz/buzz/fizzBuzz if number is a multiple of 3, 5 or both respectively

for i in {1..100}
do
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done    