#!/usr/bin/env bash
# This script displays "Best School" 10 + "Hi" at the 9th iteration times using a while loop

i=0
while [ $i -ne 10 ]
do
	echo "Best School"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	i=$((i + 1))
done
