#!/usr/bin/env bash
# Script displays 1..20 and "bad luck from China/Japan/Italy" after the 4th, 9th and 17th iterations respectively

i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		4)
		echo "bad luck from China"
		;;
		9)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
		*)
		;;
	esac
	i=$((i + 1))
done
