#!/usr/bin/env bash
# Script resolves localhost and facebook.com to 127.0.0.2(from 127.0.0.1)  and 8.8.8.8 respectively

cp /etc/hosts ~/hosts.new
sed -i "s/^127.0.0.*$/127.0.0.2\tlocalhost\n8.8.8.8 facebook.com/" ~/hosts.new
cp -f ~/hosts.new /etc/hosts